football_club/urls.py
from django.urls import path
from .views import *

app_name = 'football_club'

urlpatterns = [
    path('', HomeShow.as_view(), name='home'),
    path('club/<slug:club_slug>/', ClubShow.as_view(), name='club'),
    path('stadium/<slug:stadium_slug>/', StadiumShow.as_view(), name='stadium'),
    path('staff/<slug:staff_slug>/', StaffShow.as_view(), name='staff'),
    path('staff/', StaffListShow.as_view(), name='staff_list'),
    path('trophy/<slug:trophy_slug>/', TrophyShow.as_view(), name='trophy'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
]

football_stat/urls.py
from django.urls import path
from .views import *

app_name = 'football_stat'

urlpatterns = [
    path('dashboard', dashboardview, name='dash'),
    path('team', team_stat, name='team'),
    path('selectTeam', individualTeamData, name='selectTeam'),

]

project_football/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from football_club.views import *
from django.views.generic import RedirectView
from django.views.static import serve 



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('football_club.urls')),
    re_path(r'^', include('football_stat.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ]
    

handler404 = pageNotFound

if settings.DEBUG:
    # import debug_toolbar

    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

    urlpatterns = [
        # path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

football_club/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Trophy(models.Model):
    name = models.CharField(max_length=64, unique=True, null=True)
    logo = models.ImageField(null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Текст", null=True)
    created = models.DateField(null=True)
    winers = models.TextField(blank=True, verbose_name="Список обладателей", null=True)
    actual_owner = models.CharField(max_length=64, unique=True, null=True)
    recordsman = models.CharField(max_length=64, unique=True, null=True)



    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('football_club:trophy', kwargs={'trophy_slug': self.slug})
    
    class Meta:
        ordering = ['name']


class Club(models.Model):
    name = models.CharField(max_length=64, unique=True)
    created = models.DateField()
    country = models.CharField(max_length=64)
    league = models.CharField(max_length=64)
    logo = models.ImageField(null=True, blank=True)
    trophy = models.ManyToManyField(Trophy, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Текст", null=True)
    trophylist = models.TextField(blank=True, verbose_name="Достижения", null=True)
    teams_photo = models.ImageField(null=True, blank=True)





    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('football_club:club', kwargs={'club_slug': self.slug})

    class Meta:
       ordering = ['name']




class Staff(models.Model):
    first_name = models.CharField(max_length=64)
    second_name = models.CharField(max_length=64)
    birthday = models.DateField()
    age = models.IntegerField()
    role= models.CharField(max_length=64)
    club = models.ForeignKey(Club, on_delete=models.PROTECT)
    logo = models.ImageField(null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Текст", null=True)
    trophylist = models.TextField(blank=True, verbose_name="Достижения", null=True)




    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('football_club:staff', kwargs={'staff_slug': self.slug})
    
    class Meta:
           ordering = ['second_name']

class Stadium(models.Model):
    name=models.CharField(max_length=64, unique=True)
    location=models.CharField(max_length=64)
    capacity=models.IntegerField()
    created = models.DateField()
    club = models.ForeignKey(Club, on_delete=models.PROTECT)
    logo = models.ImageField(upload_to='', null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Текст", null=True)
    bestgames = models.TextField(blank=True, verbose_name="Лучшие матчи", null=True)



    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('football_club:stadium', kwargs={'stadium_slug': self.slug})

    
    class Meta:
           ordering = ['name']

football_club/views.py
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.template.response import TemplateResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.paginator import Paginator

from django.db.models import Q # новый


# Create your views here.

def contact(request):
    return HttpResponse("Обратная связь")

def login(request):
    return HttpResponse("Авторизация")


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class HomeShow(ListView):
    model = Club
    template_name = 'club/index.html'
    context_object_name = 'clubs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'stadium': Stadium.objects.order_by('name'),
        })
        return context

    def get_queryset(self):
        return Club.objects.order_by('name')


class ClubShow(DetailView):
    model = Club
    template_name = 'club/club.html'
    slug_url_kwarg = 'club_slug'
    context_object_name = 'club'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'stadium': Stadium.objects.order_by('name'),
        })
        context['title'] = context['club']

        return context


class StadiumListShow(ListView):
    model = Stadium
    template_name = 'club/_navbar.html'
    context_object_name = 'stadium'

class StadiumShow(DetailView):
    model = Stadium
    template_name = 'club/stadium.html'
    slug_url_kwarg = 'stadium_slug'
    context_object_name = 'stadium'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['stadium']
        return context

class StaffListShow(ListView):
    model = Staff
    template_name = 'club/staff_list.html'
    slug_url_kwarg = 'staff_slug'
    context_object_name = 'staff'


class StaffShow(DetailView):
    model = Staff
    template_name = 'club/staff.html'
    slug_url_kwarg = 'staff_slug'
    context_object_name = 'staff'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['staff']
        return context
    
class TrophyListShow(ListView):
    model = Trophy
    template_name = 'club/_navbar.html'
    context_object_name = 'trophy'

class TrophyShow(DetailView):
    model = Trophy
    template_name = 'club/trophy.html'
    slug_url_kwarg = 'trophy_slug'
    context_object_name = 'trophy'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = context['trophy']
        return context


class SearchResultsView(ListView):
    template_name = 'search_results.html'
    model = Stadium

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('search')

        context = super(SearchResultsView, self).get_context_data(**kwargs)
        context.update({
            'club': Club.objects.filter( Q(name__icontains=query) | Q(country__icontains=query)).order_by('name'),
            'staff': Staff.objects.filter( Q(first_name__icontains=query) | Q(second_name__icontains=query)).order_by('second_name'),
            'stadium': Stadium.objects.filter( Q(name__icontains=query) | Q(location__icontains=query)).order_by('name'),
            'trophy': Trophy.objects.filter(name__icontains=query).order_by('name'),
        })
        return context 

football_club/templates/_navbar.html
{% load all_stadium %}
{% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
</head>
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-danger"> -->
<nav class="navbar navbar-expand-lg my-navbar navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"> <img src="{% static 'image\index\Premier_League_Logo.png' %}" class = "img-fluid my-navbar-logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/"> <i class="fas fa-home"></i> Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'football_club:staff_list' %}"><i class="fas fa-user-circle"></i> Известные личности</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'football_stat:dash' %}"> <i class="fas fa-clipboard-list"></i> Статистика v1</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'football_stat:team' %}"> <i class="fas fa-clipboard-list"></i> Статистика v2</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fab fa-hive"></i> Стадионы
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% stadium_list %}
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fas fa-trophy"></i> Кубки
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               {% trophy_list %}
            </ul>
          </li>
        </ul>

        <ul class="navbar-nav mb-2 mb-lg-0">        
          <li class="nav-item mode">
            <a class="nav-link text-align: right" href="#" onclick="switchTheme()">
                <i class="fas fa-moon dark-icon"></i>
                <i class="fas fa-sun light-icon"></i>
            </a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'football_club:search_results' %}" method="GET">
          <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <script src="{% static 'js/index.js' %}"></script>

football_club/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block title %}
            Base title
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>        
        <!-- charts -->
        <script src="https://d3js.org/d3.v4.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
        
    </head>
        <body>
            {% include '_navbar.html' %}
            <div>         
            {% block body %}
            Base page
            {% endblock %}
            {% if page_obj.has_other_pages %}
            <nav class="list-pages">
                <ul>
                    {% if page_obj.has_previous %}
                    <li class="page-num">
                        <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
                    </li>
                    {% endif %}
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <li class="page-num page-num-selected">{{ p }}</li>
                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
                            <li class="page-num">
                                <a href="?page={{ p }}">{{ p }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-num">
                            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            </div>
            <div id="footer" class="row mt--2">
                <div style="text-align: justify; margin-top: 25px; margin-bottom: 0px;" class="text-center my-text" > 2021 </div>
                <div class="text-center my-footer" style="margin-bottom: 0px" > 
                    <div class="my-icon"><i class="fab fa-python"></i></div>
                    <div class="my-icon">django</div>
                    <div class="my-icon"><i class="fab fa-bootstrap"></i></div>
                </div>
            </div>
            <script type="text/javascript" src="{% static 'js/jquery.gallery.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/modernizr.custom.53451.js' %}"></script>
            <script type="text/javascript">
                $(function() {
                    $('#dg-container').gallery();
                });
            </script>
    </body> 
</html>

football_club/templates/search_results.html
<!-- templates/search_results.html -->
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}
            Team search
        {% endblock %}
    </head>
    <body>
        {% block body %}
        <div class="container">
            </br>
                <h1 class="text-center my-text" style="font-family: 'Roboto' sans-serif;">Search results</h1>
            </br>        
                {% for team in club %}
                    <div> <a style="text-decoration: none;font-size: 25px;" class = "my-text" href="{{ team.get_absolute_url }}"><img src="{{ team.logo.url }}" class="rounded my-logo"> <span class="my-text">{{team.name}}</span></a></div>
                {% endfor %}
                {% for arena in stadium %}
                    <div> <a style="text-decoration: none;font-size: 25px;" class = "my-text" href="{{ arena.get_absolute_url }}"><img src="{{ arena.logo.url }}" class="rounded my-logo"> <span class="my-text">{{arena.name}}</span></a></div>
                {% endfor %}
                {% for person in staff %}
                    <div> <a style="text-decoration: none; font-size: 25px;" class = "my-text" href="{{ person.get_absolute_url }}"><img src="{{ person.logo.url }}" style="max-height: 80px; max-width:80px;margin: 10px;" class="rounded"> <span class="my-text">{{person.first_name}}</span></a></div>
                {% endfor %}
        </div> 
        {% endblock %}
    </body>
</html>